### ISSUE TITLE
Add filters for tasks

### ISSUE THREAD

**Issue by mohsenkhosroanjam** [harshad57/DevDash#3]
**Description:**
As a user, I want to filter my tasks based on their status.

**Actual result:**
There is no filter. As a user, I should scroll all tasks to find the completed and uncompleted tasks.

**Expected result:**
As a user, I can filter my tasks based on their status. If I choose completed filter, only completed tasks will be shown. If I choose uncompleted filter, only uncompleted tasks will be shown.
![image](https://github.com/user-attachments/assets/fe05c322-08d6-4692-b1a0-f5ada0c60357)

**Comment by harshad57** [comment]
Thank you for providing a detailed description! I'll start working on this.
